### ISSUE TITLE
Question : why render chart as image instead of canvas /svg

### ISSUE THREAD

**Issue by nvcken** [shayne/react-native-webview-js-context#1]
As this component make able to integrate webview on react-native so I wonder can we render chart to canvas / svg on webview control. So that we can use D3 or any third part charts js lib.

Thanks for help

**Comment by shayne** [comment]
My initial inspiration was to render SVG natively, taken from the web js-context. Unfortunately I didn't know of a suitable SVG component that was compatible with SVG HTML mark-up. If you know of one or wish to parse the SVG string from the web js-context you certainly could. That said, SVG support is beyond the scope of this component.

To see what I mean, here's how you could get the SVG from Google Charts:

``` javascript
  var e = document.getElementById('chart_div');
  resolve(e.getElementsByTagName('svg')[0].parentNode.innerHTML));
```
